// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XepLichGiangDay.Api.Data;

#nullable disable

namespace XepLichGiangDay.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.BoMon", b =>
                {
                    b.Property<int>("MaBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_bo_mon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBoMon"));

                    b.Property<string>("TenBoMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_bo_mon");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_khoa");

                    b.HasKey("MaBoMon");

                    b.ToTable("bo_mon", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.ChiTietThoiKhoaBieu", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<int>("DenTuan")
                        .HasColumnType("int")
                        .HasColumnName("den_tuan");

                    b.Property<int>("MaLopHocPhan")
                        .HasColumnType("int")
                        .HasColumnName("ma_lop_hoc_phan");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phong_hoc");

                    b.Property<int>("Thu")
                        .HasColumnType("int")
                        .HasColumnName("thu");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("int")
                        .HasColumnName("tiet_bat_dau");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("int")
                        .HasColumnName("tiet_ket_thuc");

                    b.Property<int>("TuTuan")
                        .HasColumnType("int")
                        .HasColumnName("tu_tuan");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaLopHocPhan");

                    b.ToTable("chi_tiet_thoi_khoa_bieu", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.DinhMucGiangVien", b =>
                {
                    b.Property<int>("MaDinhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dinh_muc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDinhMuc"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<int>("SoTietToiDa")
                        .HasColumnType("int")
                        .HasColumnName("so_tiet_toi_da");

                    b.Property<int>("SoTietToiThieu")
                        .HasColumnType("int")
                        .HasColumnName("so_tiet_toi_thieu");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDinhMuc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKy");

                    b.ToTable("dinh_muc_giang_vien", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("ChucDanh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chuc_danh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ho_ten");

                    b.Property<int?>("MaBoMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_bo_mon");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaBoMon");

                    b.ToTable("giang_vien", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.HocKy", b =>
                {
                    b.Property<int>("MaHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocKy"));

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int")
                        .HasColumnName("ma_nam_hoc");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_hoc_ky");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHocKy");

                    b.HasIndex("MaNamHoc");

                    b.ToTable("hoc_ky", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.HocPhan", b =>
                {
                    b.Property<int>("MaHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_phan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocPhan"));

                    b.Property<int?>("MaBoMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_bo_mon");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_hoc_phan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHocPhan");

                    b.HasIndex("MaBoMon");

                    b.ToTable("hoc_phan", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.KetQuaXepLich", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ket_qua");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<double>("DiemPhat")
                        .HasColumnType("float")
                        .HasColumnName("diem_phat");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<int>("MaLopHocPhan")
                        .HasColumnType("int")
                        .HasColumnName("ma_lop_hoc_phan");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaLopHocPhan");

                    b.ToTable("ket_qua_xep_lich", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.LichBanGiangVien", b =>
                {
                    b.Property<int>("MaLichBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_ban");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichBan"));

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("den_ngay");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<int>("Thu")
                        .HasColumnType("int")
                        .HasColumnName("thu");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("int")
                        .HasColumnName("tiet_bat_dau");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("int")
                        .HasColumnName("tiet_ket_thuc");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("tu_ngay");

                    b.HasKey("MaLichBan");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKy");

                    b.ToTable("lich_ban_giang_vien", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.LichSuImport", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_su");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<DateTime>("NgayImport")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_import");

                    b.Property<int>("SoDongLoi")
                        .HasColumnType("int")
                        .HasColumnName("so_dong_loi");

                    b.Property<int>("SoDongThanhCong")
                        .HasColumnType("int")
                        .HasColumnName("so_dong_thanh_cong");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_file");

                    b.Property<int>("TongSoDong")
                        .HasColumnType("int")
                        .HasColumnName("tong_so_dong");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaHocKy");

                    b.ToTable("lich_su_import", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.LopHocPhan", b =>
                {
                    b.Property<int>("MaLopHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lop_hoc_phan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHocPhan"));

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<int>("MaHocPhan")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_phan");

                    b.Property<string>("MaLopHocPhanTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ma_lop_hoc_phan_truong");

                    b.Property<int>("SoLuongSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_sinh_vien");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_lop");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLopHocPhan");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaHocPhan");

                    b.ToTable("lop_hoc_phan", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.NamHoc", b =>
                {
                    b.Property<int>("MaNamHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nam_hoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNamHoc"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TenNamHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_nam_hoc");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaNamHoc");

                    b.ToTable("nam_hoc", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.NangLucGiangDay", b =>
                {
                    b.Property<int>("MaNangLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nang_luc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNangLuc"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    b.Property<int>("MaHocPhan")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_phan");

                    b.Property<int>("MucDoChuyenMon")
                        .HasColumnType("int")
                        .HasColumnName("muc_do_chuyen_mon");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaNangLuc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocPhan");

                    b.ToTable("nang_luc_giang_day", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ho_ten");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vai_tro");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.NguyenVongGiangVien", b =>
                {
                    b.Property<int>("MaNguyenVong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguyen_vong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguyenVong"));

                    b.Property<string>("LoaiNguyenVong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_nguyen_vong");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<int>("MucDo")
                        .HasColumnType("int")
                        .HasColumnName("muc_do");

                    b.Property<string>("NoiDungGoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung_goc");

                    b.Property<int?>("Thu")
                        .HasColumnType("int")
                        .HasColumnName("thu");

                    b.Property<int?>("TietBatDau")
                        .HasColumnType("int")
                        .HasColumnName("tiet_bat_dau");

                    b.Property<int?>("TietKetThuc")
                        .HasColumnType("int")
                        .HasColumnName("tiet_ket_thuc");

                    b.Property<double>("TrongSoPhat")
                        .HasColumnType("float")
                        .HasColumnName("trong_so_phat");

                    b.HasKey("MaNguyenVong");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKy");

                    b.ToTable("nguyen_vong_giang_vien", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.PhanCongGiangDay", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phan_cong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<double>("DiemPhat")
                        .HasColumnType("float")
                        .HasColumnName("diem_phat");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("ma_giang_vien");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<int>("MaLopHocPhan")
                        .HasColumnType("int")
                        .HasColumnName("ma_lop_hoc_phan");

                    b.Property<string>("NguonPhanCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguon_phan_cong");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaLopHocPhan");

                    b.ToTable("phan_cong_giang_day", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.RangBuocHocKy", b =>
                {
                    b.Property<int>("MaRangBuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_rang_buoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaRangBuoc"));

                    b.Property<string>("LoaiRangBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_rang_buoc");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenRangBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_rang_buoc");

                    b.Property<double>("TrongSoPhat")
                        .HasColumnType("float")
                        .HasColumnName("trong_so_phat");

                    b.HasKey("MaRangBuoc");

                    b.HasIndex("MaHocKy");

                    b.ToTable("rang_buoc_hoc_ky", (string)null);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.ChiTietThoiKhoaBieu", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.LopHocPhan", null)
                        .WithMany()
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.DinhMucGiangVien", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.GiangVien", null)
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.GiangVien", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.BoMon", null)
                        .WithMany()
                        .HasForeignKey("MaBoMon")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.HocKy", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.NamHoc", null)
                        .WithMany()
                        .HasForeignKey("MaNamHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.HocPhan", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.BoMon", null)
                        .WithMany()
                        .HasForeignKey("MaBoMon")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.KetQuaXepLich", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.GiangVien", null)
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.LopHocPhan", null)
                        .WithMany()
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.LichBanGiangVien", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.GiangVien", null)
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.LichSuImport", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.LopHocPhan", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocPhan", null)
                        .WithMany()
                        .HasForeignKey("MaHocPhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.NangLucGiangDay", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.GiangVien", null)
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocPhan", null)
                        .WithMany()
                        .HasForeignKey("MaHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.NguoiDung", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.GiangVien", null)
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.NguyenVongGiangVien", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.GiangVien", null)
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.PhanCongGiangDay", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.GiangVien", null)
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XepLichGiangDay.Api.Models.Entities.LopHocPhan", null)
                        .WithMany()
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XepLichGiangDay.Api.Models.Entities.RangBuocHocKy", b =>
                {
                    b.HasOne("XepLichGiangDay.Api.Models.Entities.HocKy", null)
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
